### ISSUE TITLE
show.html 라이브서버 실행시 학년, 학기에 대한 명확한 표시가 필요해 보입니다.

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-js#105]
1f43b94 버전에서 show.html 실행 시 화면입니다.
<img width="1494" alt="스크린샷 2024-06-04 14 18 06" src="https://github.com/oss2024hnu/coursegraph-js/assets/127175733/a82cc898-ffb7-45e7-85cb-59e02f832204">
학년, 학기에 대한 구분선이나 색상 구분이 필요해 보이며, 몇 학년인지, 몇 학기인지 글로도 표시하는 것이 좋아보입니다.

**Comment by kyagrd** [comment]
라이브서버라는 말은 내용상 상관이 없어서 제목 수정했습니다
