### ISSUE TITLE
subject-chart.html 실행 시 과목 별 선의 색상을 다르게 하는 것이 좋아보입니다.

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-js#106]
1f43b94 버전에서 subject-chart.html 실행 시 화면입니다.
<img width="1252" alt="스크린샷 2024-06-04 14 27 12" src="https://github.com/oss2024hnu/coursegraph-js/assets/127175733/b6f329af-0b17-4d06-9b91-33692af56718">
선이 겹쳐 가시성이 떨어지므로 과목마다 선의 색상을 다르게 하는 것이 좋아 보입니다.

**Comment by kyagrd** [comment]
최근 https://github.com/oss2024hnu/coursegraph-js/pull/107 등의 PR들로 해결

근데 근본적으로는 색상 구분 없이 잘 알아볼 수 있는 모양의 그래프라 생성되게 하는 것이 근본적인 해결책이라고 생각합니다.

정보 구분의 의미가 없는 색상 추가는 정보 전달의 측면에서는 바람직하다고 생각하진 않아서요.
