### ISSUE TITLE
subject-chart.html에도 데이터가 많아 검색바가 있으면 좋겠습니다

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-js#112]
![image](https://github.com/oss2024hnu/coursegraph-js/assets/127175733/4c3c7d7f-f337-473c-b984-ca1c62c4300e)
f05e1cd버전에서 실행 화면입니다
데이터가 많은 subject-chart.html에도 show.html처럼 과목을 검색할 수 있는 검색바가 있으면 좋을 것 같습니다!

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/113 로 해결
