### ISSUE TITLE
show.html 출력 자체를 바꿔야합니다.

### ISSUE THREAD

**Issue by yjs02330** [oss2024hnu/coursegraph-js#114]
현재 main.js 코드가 처음부터 특정 파일의 경로를 지정해 로드하는 코드로 이루어져있는데
파일 선택을 통해 /data/ 안에 있는 json 체계도를 불러오는 쪽으로 만들어야합니다.

**Comment by kyahnu** [comment]
이건 기본적으로 하나를 보여주고 필요하다면 선택해서 바꿀 수 있도록 하는 거니까 처음에 기본적으로 하나 보여주는 것 자체는 문제가 없다고 생각합니다. 그리고 파일을 불러오는 것은 이미 기능이 구현중이고, 또 기능이 제대로 동작하는지 확실하지 않은 상황에 대해서는 이미 관련 이슈가 있어서 이 이슈는 중복성이 있으므로 반려합니다.

**Comment by kyahnu** [comment]
관련 이슈인 https://github.com/oss2024hnu/coursegraph-js/issues/78 에서 논의해 주세요
