### ISSUE TITLE
mermaid초기화 중 에러가 발생할 시 피드백이 필요합니다. 

### ISSUE THREAD

**Issue by Retic02** [oss2024hnu/coursegraph-js#116]
console log 등을 통해서 사용자에게 알려줄 필요가 있습니다.

**Comment by kyahnu** [comment]
실제로 에러가 발생하는 경우가 재현 가능한가요? 에러가 발생하면 어떤 상황이 되나요? 크롬 등 브라우저 developer tool 콘솔에서 확인이 현재는 불가능한 사유가 뭔가요?

추상적으로 아무 이슈에 대해 console log 가 필요하다는 이슈는 무한히 모든 줄의 자바스크립트 코드에 대해 만들어낼 수 있기 때문에 지금 어떤 점에서 확인이 어려운 오작동이 실제로 있는지, 있다면 어떤 경우에 발생하는지, 발생했는데도 크롬 브라우저 developer tool 콘솔에서 확인이 안되는 건지 ... 자세한 상황을 제시하지 않는다면 이 이슈는 부적절하다고 판단되어 반려하겠습니다.

**Comment by kyagrd** [comment]
답변이 없는 것으로 구체적 사안이 아니라 판단하고 반려하겠습니다.
