### ISSUE TITLE
화살표의 가시성이 좋지않습니다

### ISSUE THREAD

**Issue by hateauk12** [oss2024hnu/coursegraph-js#118]
화살표들이 중구난방으로 퍼져있어 이 화살표들을 겹치되 색상을 구분지어 연결을 해주면 더욱 가시성이 높아질거 같습니다

**Comment by kyagrd** [comment]
비슷한 중복 이슈를 반복 생성하지 맙시다 반려합니다. 바로 직전에도 화살표 관련 이슈가 이미 올라왔습니다. 거기서 같이 논의해 주세요.
