### ISSUE TITLE
파이썬으로 웹서버 실행하는 README 내용에 불필요한 이미지 활용

### ISSUE THREAD

**Issue by kyagrd** [oss2024hnu/coursegraph-js#123]
현재 0aa97b22ce8e695fc169c7cd18e54b13a2a05925 버전 기준으로

최근 들어온 PR에 마크다운의 기능을 활용해 충분히 텍스트로 할 수 있는 명령어 내용을 불필요하게 이미지 캡춰로 처리하여 Ctrl-C, Ctrl-V로 복사, 붙여넣기도 안되고 검색도 되지 않는 등 정보의 질이 이미지를 활용함으로써 오히려 저해되어 있는 내용으로 문서가 작성되었습니다.

이를 마크다운의 기능을 활용해 텍스트 형태로 수정하는 것이 필요합니다.

참고: https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/127 로 해결
