### ISSUE TITLE
인터랙티브 그래프 기능 

### ISSUE THREAD

**Issue by leeseungho55** [oss2024hnu/coursegraph-js#124]
그래프를 클릭하거나 호버할 때 추가 정보를 표시하는 인터랙티브 그래프를 만드는 것을 의미.
예를 들어, 그래프의 노드를 클릭하면 해당 노드의 정보를 모달 창에 표시

// 예시 코드
document.querySelectorAll('.node').forEach(node => {
    node.addEventListener('click', function() {
        const nodeName = this.textContent;
        // 여기에 해당 노드의 정보를 표시하는 코드 추가
    });
});

**Comment by kyahnu** [comment]
여러 개의 html 파일과 js 파일이 있는데 무슨 파일인지도 밝히지 않고 이렇게 알아보기 힘든 내용은 (저도 잘 모르겠으면 다른 학생들도 마찬가지일 것이라 보기 때문에) 반려합니다.
