### ISSUE TITLE
전공필수, 전공기초 CSS색상 및 border 관련 표시

### ISSUE THREAD

**Issue by shofjablas** [oss2024hnu/coursegraph-js#13]
전공필수랑 전공 기초 다른 색상으로 표시해서 하면 좋을거같습키다. 또 전공필수의 경우 전공선택보다 border의 두께를 더 두껍게 표시해서 설정해주면 전공기초랑 비교하기 좋을거같습니다.

**Comment by kyagrd** [comment]
이거 PR이 들어와서 https://github.com/oss2024hnu/coursegraph-js/pull/100 등으로 해결된 듯 합니다
