### ISSUE TITLE
js에서 두가지 버전으로 개발할 필요는 없다고 생각합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-js#130]
subject-chart.html
show.html이 두 가지 버전으로 개발이 되고 있는데, python도 따로 개발되고 있기 때문에 js에서 두가지 버전으로 개발할 필요가 없다고 생각합니다.

**Comment by kyahnu** [comment]
이거는 두 가지 버전이 아니라 다른 라이브러리를 시도해 보는 겁니다. 여러 사람이 참여하기 때문에 동시에 여러 가지 방법을 탐색해 보는 겁니다. 나중에 어느 한쪽이 많이 개발되고 완성도가 높아지면 한쪽을 버리고 한쪽으로 하지만 우리는 지금 일정상 학기말까지 그렇게 되지 않을 거 같거든요. 혹시 통합할 방법을 제시하는 게 아니라면, 기존에 두개로 진행되고 있는 이유를 파악하지 못했을 뿐으로 보이므로, 이슈거리가 보기 힘들므로 반려합니다.
