### ISSUE TITLE
가독성을 위해 show.html의 그래프를 화면 가운데로 정렬하는 것이 좋을 것 같습니다. 

### ISSUE THREAD

**Issue by sominoh** [oss2024hnu/coursegraph-js#131]
또한 과목명 또한 틀 가운대로 정렬하는 것이 좋을 것 같습니다. 
![이슈1](https://github.com/oss2024hnu/coursegraph-js/assets/145252436/42240394-58e7-4b02-a6bd-297a9c1295e4)

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/134 로 해결
