### ISSUE TITLE
과목 세부 정보가 표시되었으면 좋겠습니다

### ISSUE THREAD

**Issue by leeseungho55** [oss2024hnu/coursegraph-js#142]
예시 코드
<script>
    const subjectDetails = {
        "웹스크립트프로그래밍": "이 과목은 웹 개발에 필요한 스크립트 언어를 배웁니다.",
        // 다른 과목의 세부 정보 추가
    };

    document.querySelectorAll('.mermaid text').forEach(node => {
        node.addEventListener('click', () => {
            const subject = node.textContent;
            if (subjectDetails[subject]) {
                alert(subjectDetails[subject]);
            }
        });
    });
</script>

**Comment by leeseungho55** [comment]
index.html

**Comment by leeseungho55** [comment]
과목 그래프 페이지에 추가

**Comment by kyahnu** [comment]
이건 프로젝트의 범위가 아닙니다. 데이터 파일 자체에 애초에 원본에 이걸 넣는 걸 고려하고 있지 않습니다.
