### ISSUE TITLE
subject-chart의 화살표 색에 대한 설명을 전공기초&공통 권장항목 버튼 옆에 배치시켰으면 좋겠습니다. 

### ISSUE THREAD

**Issue by sominoh** [oss2024hnu/coursegraph-js#143]
이수 체계도 화살표의 색을 왜 구분해놨는지에 대한 설명이 필요합니다.

**Comment by sominoh** [comment]
![이슈2](https://github.com/oss2024hnu/coursegraph-js/assets/145252436/5d38d0d6-e5b2-4f2a-88bd-26c71a5b8920)

**Comment by kyahnu** [comment]
화살표 색은 의미가 없습니다. 그래서 이 이슈는 그냥 닫습니다.
