### ISSUE TITLE
subject-chart 학년별 박스간 간격을 일정하게 조정하는 것이 필요합니다. 

### ISSUE THREAD

**Issue by sominoh** [oss2024hnu/coursegraph-js#144]
현재는 간격이 일정하지 않아 이수체계도 가독성이 좋지 않습니다. 
![이슈3](https://github.com/oss2024hnu/coursegraph-js/assets/145252436/29154965-1eea-4a97-ac94-41cbb3389343)

**Comment by kyahnu** [comment]
이런 거 안받는다고요 이제 이슈로
