### ISSUE TITLE
학년, 학기를 나타내는 텍스트 형태에 볼드를 넣거나 폰트 크기를 키우면 좋을 것 같습니다. 

### ISSUE THREAD

**Issue by Nhyojeong** [oss2024hnu/coursegraph-js#146]
![image](https://github.com/oss2024hnu/coursegraph-js/assets/146164867/312e9a5a-6459-4f82-8603-83ac311819ab)

subject 페이지의 1학년, 2학년, 3학년, 4학년과 같이 학년을 알리는 텍스트와 1학년 1학기 등 학기를 알리는 텍스트가 다른 텍스트들과 같습니다.

이에 볼드 처럼 텍스트의 굵기를 조정하거나 폰트 크기를 수정하면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
심미적 기능은 더 이상 받지 않겠다고 공지했습니다.
