### ISSUE TITLE
학과별(컴퓨터공학과, 멀티미디어공학과, AI학과) json 데이터 파일 생성

### ISSUE THREAD

**Issue by hy2oning** [oss2024hnu/coursegraph-js#15]
파이썬 언어와 같이 학과별(컴퓨터공학과, 멀티미디어공학과, AI학과) json 데이터 파일을 만들어 분류해야할것 같습니다.

**Comment by shofjablas** [comment]
컴퓨터공학과 이수체계도를 기반으로 json파일 만들었습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/17 로 컴공은 진행

**Comment by hy2oning** [comment]
#83 #87 로 해결
