### ISSUE TITLE
index.html 에서 이미지에 있는 로고가 잘려 보입니다. 

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-js#158]
![image](https://github.com/oss2024hnu/coursegraph-js/assets/127175733/a0715280-3c13-4f95-82a7-f91c9f502f9d)
3a45774 버전에서 오른쪽 상단에 있는 한남대학교 로고가 잘려보입니다. 이미지가 잘려보이지 않도록 margin-top을 설정하는 것이 좋아보입니다

**Comment by kyahnu** [comment]
반려합니다. 기능 개선이 아닌 미적 개선은 더 이상 받지 않습니다.
