### ISSUE TITLE
컴퓨터공학과 홈페이지 이수체계도를 기반으로 json파일 만들었습니다.

### ISSUE THREAD

**Issue by shofjablas** [oss2024hnu/coursegraph-js#16]
json 파일안에는 크게 학년별 학기, 전공기초(필수), 공통권장으로 나눠 만들었습니다.

https://ce.hannam.ac.kr/roadmap/

![image](https://github.com/oss2024hnu/coursegraph-js/assets/97035336/3c21ee47-d59d-40dc-adf6-9a30b649cfb5)
![image](https://github.com/oss2024hnu/coursegraph-js/assets/97035336/53ad15d4-9f57-4245-a094-db8cbc38f366)

**Comment by shofjablas** [comment]
커밋했는데 파일 올라갔나요?

**Comment by shofjablas** [comment]
컴퓨터공학과 json 파일 만들어놔서 필요시 사용하면 될거같습니다.

**Comment by kyahnu** [comment]
아니 ... 이미 만든 건 이슈가 아니죠 원래 할 계획이나 요청사항을 이슈로 올리는 겁니다. 이슈로 적절하지 않으니 반려합니다.
