### ISSUE TITLE
사용하지 않거나 중복된 data 폴더의 파일들에 대해 정리가 필요합니다.

### ISSUE THREAD

**Issue by DoongDoongSJ** [oss2024hnu/coursegraph-js#162]
초기에 사용되었지만 이제는 잘 사용하지 않는 input.json를 삭제하고, 컴퓨터공학과의 과목 정보인 courses.json과 cs-data.json를 통합할 필요가 있어보입니다

**Comment by kyahnu** [comment]
이제는 yaml로부터 생성할 것이기 때문에 이 이슈는 더 이상 유효하지 않습니다.
