### ISSUE TITLE
show.html에서 파일을 불러와서 출력한 다음 새로운 파일을 불러오면 초기화하고 새로운 표를 그리도록 수정해야합니다.

### ISSUE THREAD

**Issue by IVEGAEUL** [oss2024hnu/coursegraph-js#163]
현재 show.html에서 파일을 불러온 다음 출력을 한 후 새로운 파일을 불러오면 이전의 데이터들이 그대로 남아있는 현상이 발생하고 있습니다. 새로운 파일을 불러오면 이전의 데이터를 삭제시키는 기능을 추가해야될 것 같습니다.

**Comment by kyagrd** [comment]
이건 이제 해결되긴 한 듯
