### ISSUE TITLE
파이썬 처럼 온보딩을 만들어서 각 html이 어떤 기능을 하는지 설명

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-js#164]
- 현재 수정 사항도 많고 참여하는 사람도 많아 코드가 어떤 기능을 하는지 헷갈리고 사용자끼리의 이해도도 다른 것 같습니다. 
- 그렇기 때문에 어떤 사항이 진행되고 있고 이 코드는 어떤 기능을 하는지 설명하면 좋을 것 같습니다. 
- 나중에 코드를 수정하고 pull request를 하더라도 좀더 코드에 대한 이해도도 높아질것 같습니다.

**Comment by kyagrd** [comment]
이거 예전에 본인이 올린 비슷한 이슈가 있어서 점수를 추가로 인정하지 않고 그냥 예전에 올린 이슈를 지우겠습니다. -.-

**Comment by kyagrd** [comment]
이번 이슈가 더 상세히 작성되어 있으니
