### ISSUE TITLE
show.html 에서 데이터를 불러오는 기능이 그래프를 그리는 main.js와 연동되어있지 않습니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-js#165]
html에서 받은 데이터 파일을 main.js에서 사용할 수 있도록 하드코딩 되어진 main.js 를 수정해야합니다.

main.js에서 show.html에서 선택된 데이터 파일의 데이터를 사용하여 그래프를 그리도록 조정해야합니다.

**Comment by kyagrd** [comment]
main.js를 삭제해 버렸으므로 이 이슈도 닫습니다
