### ISSUE TITLE
검색 기능 오류 알림창에 대한 패치 필요함

### ISSUE THREAD

**Issue by yjs02330** [oss2024hnu/coursegraph-js#173]
(마지막만 읽어도 됩니다.)
만약 '프로그래밍'이라는 검색어를 입력했을 시 위에서부터 차례대로 검색하지만 마지막 검색어가 나온 후에 다음으로 넘어갈때 '일치하는 과목을 찾을 수 없습니다.' 라는 오류창 뜨는데 이는 적합하지 않다고 생각합니다.

검색에 단어가 포함 되어 있지 않을 시에만 오류창이 뜨고,  단어가 있다면 순서대로 검색하되, 나미작 검색이 끝나면 다시 처음부터 검색되게끔 바꾸는게 좋을거같습니다.

**Comment by kyahnu** [comment]
끝자리 92 맞죠?
