### ISSUE TITLE
페이지 간 이동 시 사용자 경험을 향상시키기 위한 부드러운 전환 효과

### ISSUE THREAD

**Issue by sungmin-99** [oss2024hnu/coursegraph-js#178]
CSS와 JavaScript를 활용하여 전환 효과를 구현
예를 들어 .fade-in과 .fade-out 클래스에 전환 효과를 설정
사용자 경험을 향상시키고, 시각적으로 더 매끄러운 페이지 전환을 제공할 수 있습니다.

**Comment by kyagrd** [comment]
이런 거 안받는다고 공지했어요 하이클래스에
