### ISSUE TITLE
파일 업로드 시 발생할 수 있는 에러 핸들링

### ISSUE THREAD

**Issue by giantsudal** [oss2024hnu/coursegraph-js#179]
1. 파일 크기 초과 에러 처리
2. 잘못된 파일 형식 에러 처리
3. 파일 읽기 오류 처리

**Comment by kyahnu** [comment]
아직 발생하지도 않은 오류인데 테스트를 해보고 나서 일단 동작하는 걸 확인하고 나서 해야지
모든 곳에 예외처리 에러핸들링을 합시다 이거는 아무 코드 아무 UI에나 하나씩 다
양산할 수 있기 때문에 구체성이 없으면 적절한 이슈로 보기 힘들므로 반려합니다.
