### ISSUE TITLE
input.html, Show.html, subject-chart.html 에서 돌아가기 버튼을 누를 시 오류가 납니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-js#180]
![image](https://github.com/oss2024hnu/coursegraph-js/assets/151762285/96048a6d-9ece-4daa-a72b-27331ff40a17)

돌아가기 버튼을 누르면 
![image](https://github.com/oss2024hnu/coursegraph-js/assets/151762285/9d75d8fa-dff8-4577-bc3c-f4b21bc19d1c)

오류가 납니다. 
++input.html, show.html, subject-chart.html 다 돌아가기 버튼을 누르면 index.html 로 돌아가는데 작동 오류가 납니다.

**Comment by kyahnu** [comment]
이미지 말고 텍스트로도 최대한 정보를 적읍시다 무슨.html 파일인지 ...

**Comment by eongeung** [comment]
> 이미지 말고 텍스트로도 최대한 정보를 적읍시다 무슨.html 파일인지 ...

수정했습니다

**Comment by kyahnu** [comment]
index.html 에는 돌아가기 버튼이 없어요 ....

**Comment by eongeung** [comment]
> index.html 에는 돌아가기 버튼이 없어요 ....

죄송합니다 확인하고 다시 변경했습니다.
