### ISSUE TITLE
show.html이 courses.json 파일을 선택해 업로드해야만 화면에 나타납니다.

### ISSUE THREAD

**Issue by kyahnu** [oss2024hnu/coursegraph-js#189]
현재 08b1935958ecbd8f4d5e33b64c9bef2274915000 버전 기준으로

https://github.com/oss2024hnu/coursegraph-js/commits/main/여러 PR을 받아들이다 보니 ...

어디서부터 요류가 생겼는지 ... 음

이게 파이썬 CLI처럼 테스트 자동화가 안 되어 있어서

그렇다고 문서화도 안 되어 있고

지금 처음에 아무것도 안나타나는 게 정상인가요? 버튼만 두 개 보이는데 이제

**Comment by SiRyung** [comment]
저는 정상적으로 다 보입니다.

**Comment by kyahnu** [comment]
courses.json을 업로드해야만 저는 보이거든요 처음에는 안보이고

**Comment by kyahnu** [comment]
이게 정상적인 동작이면 파일을 선택해서 올리라고 안내 메시지가 좀 필요할 거 같습니다. 갑자기 빈 화면이 나오니 당황해서 ㅎㅎ

**Comment by SiRyung** [comment]
json을 통일하는게 우선적으로 되어야 할 것 같습니다.
아직 파일을 선택하고 선택한 파일의 이름만 보이는 것 같은데, 구현을 한다 해도
통일되지 않은 자료로 그리려고 하면 작동하지 않을 것 같습니다.
