### ISSUE TITLE
main.js 를show.js로 이름 변경할것을 건의 드립니다.

### ISSUE THREAD

**Issue by vegahouse102** [oss2024hnu/coursegraph-js#198]
현제 main.js를 show.html에서만 존재하기때문에 show.js로 바꾸는게 좋을거 같습니다

**Comment by vegahouse102** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/197

**Comment by kyagrd** [comment]
이건 반려합니다. 지금 마감이 얼마 남지 않고 여러명이 작업하고 있어서 이거 충돌을 양산하고 막판에 특히 더 참여가 많아질텐데 현실적으로 무리입낟. 그냥 이슈에 대한 점수만 인정하겠습니다.

**Comment by kyagrd** [comment]
이거 데이터 형식으로 혼란을 겪다 보니 main을 날려버리는 게 이슈를 제기했던 이유와는 조금 다른 이유로도 할만한 일이 되어서 지금 보니 좋은 제안이어서 다시 점수 부여합니다.
