### ISSUE TITLE
json 파일들을 모아둘 소스 폴더를 만들고 이런 경로를 코드에 추가했으면 좋겠습니다.

### ISSUE THREAD

**Issue by LemonVein** [oss2024hnu/coursegraph-js#20]
현재 과목들의 정보들이 들어가있는 json 파일을

따로 소스 폴더를 만들어서 관리하는 것이 좋을것 같습니다.

추후에 추가될 테스트 json 파일들을 관리할 때도 편리할것같습니다.

**Comment by hy2oning** [comment]
#53  으로 해결
