### ISSUE TITLE
Show.html 용 json파일과 subject.html용 json구성이 다릅니다

### ISSUE THREAD

**Issue by SiRyung** [oss2024hnu/coursegraph-js#202]
Show.html용 json과 subject.html 구성이 많이 다릅니다

Show.html에서 작업 하는 사람도 많기에 이 작업 형태에 맞는 json 구성으로 바꿔주는 프로그램이 필요할 것 같습니다

**Comment by SiRyung** [comment]
문제점은 그대로고, 트랙과 마이크로디그리를 무시하고 일단 그릴 수 있게 다시 만들어서
PR 올리겠습니다.

문제점은 YAML파일중 선수과목이 없는 파일들이 있어, 그래프를 그릴 때 화살표가 나오지 않습니다.
YAML파일에 선수과목을 추가하여야만 YAML to JSON을 돌렸을때 화살표까지 정상적으로 나올 것 같습니다.

**Comment by SiRyung** [comment]
Show.html용으로 만들었는데 subject.html용과 구성이 많이 달라 만들어보았습니다

**Comment by kyagrd** [comment]
yaml에서 자동생성하는 것에 맞추는 것이 좋을 거 같네요
