### ISSUE TITLE
실시간 협업 기능 추가 

### ISSUE THREAD

**Issue by leeseungho55** [oss2024hnu/coursegraph-js#214]
여러 사용자가 동시에 이수체계도를 편집할 수 있는 실시간 협업 기능을 추가

// 예시코드(show,html)

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
<script>
    const socket = io.connect('http://localhost:3000');
    socket.on('updateChart', function(data) {
        // 코드 갱신 로직
    });

    function sendUpdate(data) {
        socket.emit('updateChart', data);
    }

    // 예: 과목 추가 시
    function addCourse(course) {
        // 과목 추가 로직
        sendUpdate({ action: 'add', course });
    }
</script>

//예시코드2(js)
const io = require('socket.io')(server);

io.on('connection', (socket) => {
    socket.on('updateChart', (data) => {
        io.emit('updateChart', data);
    });
});

**Comment by kyagrd** [comment]
뭐하자는 거죠?
