### ISSUE TITLE
사용자 피드백 시스템 구축 관련 내용

### ISSUE THREAD

**Issue by leeseungho55** [oss2024hnu/coursegraph-js#216]
학생들이 과목 및 이수 체계도에 대해 피드백을 남길 수 있는 시스템을 구축하여, 사용자 경험을 지속적으로 개선

 //예시 코드- 피드백 폼html
<div id="feedbackForm">
    <h2>피드백 남기기</h2>
    <form id="submitFeedback">
        <label for="course">과목:</label>
        <select id="course" name="course">
            <option value="course1">웹스크립트프로그래밍</option>
            <option value="course2">프로그래밍실습</option>
            
        </select>
        <label for="rating">평점:</label>
        <input type="number" id="rating" name="rating" min="1" max="5">
        <label for="comments">의견:</label>
        <textarea id="comments" name="comments"></textarea>
        <button type="submit">제출</button>
    </form>
    <div id="feedbackMessage"></div>
</div>

//예시코드-피브백 제출 JS
document.getElementById('submitFeedback').addEventListener('submit', function(event) {
    event.preventDefault();

    const feedbackData = {
        course: document.getElementById('course').value,
        rating: document.getElementById('rating').value,
        comments: document.getElementById('comments').value,
    };

    fetch('/submitFeedback', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(feedbackData)
    })
    .then(response => response.json())
    .then(data => {
        document.getElementById('feedbackMessage').textContent = '피드백이 성공적으로 제출되었습니다!';
    })
    .catch(error => {
        console.error('Error:', error);
        document.getElementById('feedbackMessage').textContent = '피드백 제출에 실패했습니다. 다시 시도해주세요.';
    });
});

//예시코드-피드백 처리 JS
const express = require('express');
const app = express();

app.use(express.json());

let feedbacks = [];

app.post('/submitFeedback', (req, res) => {
    const feedback = req.body;
    feedbacks.push(feedback);
    res.json({ message: '피드백이 성공적으로 제출되었습니다!' });
});

app.get('/getFeedbacks', (req, res) => {
    res.json(feedbacks);
});

const server = app.listen(3000, () => {
    console.log('Server is running on port 3000');
});

**Comment by kyagrd** [comment]
??? 뭐하는 내용인지 모르겠습니다. 갑자기 왜 익스프레스 백엔드 코드를 사용하자는 건지도 모르겠교
