### ISSUE TITLE
이전 올린 코드에 개선 사항 추가

### ISSUE THREAD

**Issue by leeseungho55** [oss2024hnu/coursegraph-js#219]
피드백 통계 대시보드 기능 추가
피드백 통계 대시보드는 제출된 피드백 데이터를 종합적으로 분석하여, 과목별 평점, 주요 개선 사항 등을 관리자 페이지에서 한눈에 확인할 수 있도록 하는 시스템

HTML (관리자 대시보드 페이지):
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>피드백 통계 대시보드</title>
    <link rel="stylesheet" href="styles.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>피드백 통계 대시보드</h1>
    <div>
        <canvas id="ratingsChart"></canvas>
    </div>
    <div id="wordCloud"></div>
    <div id="improvementList"></div>
    <script src="dashboard.js"></script>
</body>
</html>

JavaScript (대시보드 시각화):
document.addEventListener('DOMContentLoaded', function () {
    fetch('/api/getFeedbacks')
        .then(response => response.json())
        .then(data => {
            // 평점 평균 계산
            const ratings = {};
            data.forEach(feedback => {
                if (!ratings[feedback.course]) ratings[feedback.course] = [];
                ratings[feedback.course].push(feedback.rating);
            });
            const avgRatings = {};
            for (let course in ratings) {
                avgRatings[course] = ratings[course].reduce((a, b) => a + b, 0) / ratings[course].length;
            }

            // 평점 차트 생성
            const ctx = document.getElementById('ratingsChart').getContext('2d');
            new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: Object.keys

**Comment by leeseungho55** [comment]
2개의 코드 모두 Show .html의 근거 새로은 기능 개선 제안

**Comment by kyagrd** [comment]
이런 식으로 이슈 가지치기하지 마세요
