### ISSUE TITLE
show.html 기존 json적용안되는 버그 

### ISSUE THREAD

**Issue by vegahouse102** [oss2024hnu/coursegraph-js#230]
기존 json이 적용이 되지 않고 오류가  뜹니다. 이 문제를 고쳤으면 좋겠습니다.

**Comment by kyagrd** [comment]
이거 중간에 해결이 되기는 했는데 이제 예전 yaml에서 변환하기 전의 형식은 사용하지 않기로 해서 어쨌든 이러나 저러나 해결됨
