### ISSUE TITLE
과목별 세세한 사항들을 확인할수 있으면 좋겠습니다

### ISSUE THREAD

**Issue by MurRuck** [oss2024hnu/coursegraph-js#232]
해당 과목에 마우스를 올려놓으면 해당 과목이 전공 필수인지 아닌지 아니면 몇학점인지 같은 그런걸 알 수 있으면 좋겠습니다

**Comment by vegahouse102** [comment]
https://github.com/oss2024hnu/coursegraph-js/issues/199
이미 있는 이슈입니다
