### ISSUE TITLE
바뀐 courses.json에 맞게 show.html을 수정

### ISSUE THREAD

**Issue by DoongDoongSJ** [oss2024hnu/coursegraph-js#239]
courses.json이 변경되었는데, 이를 다시 되돌리는 것은 적절하지 않습니다.
빠진 트랙과 마이크로디그리를 반영한 뒤 show.html이 동작하도록 수정되는 것이 적절해보입니다.

**Comment by kyagrd** [comment]
이제는 사용하지 않는 형식이고 다른 파일과 겹치기 때문에 제거했으므로 이 이슈는 해결되었습니다.
