### ISSUE TITLE
다크 모드를 사용할 수 있는 버튼 추가 

### ISSUE THREAD

**Issue by Jae20230112** [oss2024hnu/coursegraph-js#241]
원래 다크 모드를 사용하던 사람들은 이수체계도를 볼 때 불편함을 느낄 수 있을 것 같습니다.
png 버튼 옆에 다크 모드를 사용할 수 있는 버튼을 추가하면 좋을 것 같습니다

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/286 로 해결
