### ISSUE TITLE
각 학년 버튼을 눌렀을 때 각 학년을 제외한 나머지 학년체계도가 불투명하게 표시되면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by Jae20230112** [oss2024hnu/coursegraph-js#247]
각 학년 버튼이 생성된 후 아무 기능을 하고 있지 않습니다.
각 학년 버튼을 눌렀을 때 각 학년을 제외한 나머지 학년체계도가 불투명하게 표시되면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/262 방금 이걸로 어느 정도 해결이 된 걸로 보입니다.
