### ISSUE TITLE
show.html 파일이 열리지 않습니다.

### ISSUE THREAD

**Issue by ohnakyu** [oss2024hnu/coursegraph-js#251]
![깃허브](https://github.com/oss2024hnu/coursegraph-js/assets/162093749/1ece2657-adb5-4096-b419-f670c57a5129)
이 사진처럼 오류가 뜨고 아무것도 뜨지 않습니다.

**Comment by vegahouse102** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/256

**Comment by kyagrd** [comment]
이거 main.js 를 없애서 해결했습니다.
