### ISSUE TITLE
show.html에서 파일을 선택했을 때 이수체계 화살표가 그려지지 않는 문제와 형식이 맞지 않는 오류 발생 

### ISSUE THREAD

**Issue by sominoh** [oss2024hnu/coursegraph-js#253]
1. 화살표가 그려지지 않음 
ai.json, me.json
![issue](https://github.com/oss2024hnu/coursegraph-js/assets/145252436/af05da05-14d3-4d2b-9977-0d0882d01d31)

2. 형식 오류 
input.json, cs.json, courses.json, [media.json]
![issue2](https://github.com/oss2024hnu/coursegraph-js/assets/145252436/68895960-650e-4e10-8f4c-4ef0e2f66c31)

**Comment by kyagrd** [comment]
화살표가 그려지지 않는 것은 원래 데이터가 없어서 그렇습니다.
그리고 이건 형식에 맞지 않는 파일을 모두 삭제해서 이이미 해결된 문제입니다.

그래서 이슈거리가 아니므로 반려합니디ㅏ
