### ISSUE TITLE
test.html 코드 구조 개선을 위한 모듈화 및 객체지향 적용

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-js#26]
- 현재 프로젝트의 코드는 유지보수가 어렵다고 판단됩니다. 
- 코드 구조를 개선하고 유연성을 높이기 위해 모듈화를 하면 좋을 것 같습니다. 
- 모듈화의 경우 예를 들어 Canvas 관련 기능은 별도의 모듈로 분리하고 , 사용자 인터페이스 관련 기능은 다른 모듈로 분리하면 좋을 것 같습니다. 
- 객체지향 프로그래밍 원칙을 적용하여 코드를 재구성하는데 관련 기능을 클래스로 정의하고 객체 간의 상호작용을 구현하여 코드의 가독성과 유지보수를 하면 좋을 것 같습니다. 
- 예를 들어 CanvasManager.js , UIManager.js 를 모듈화하여 구현하고 main.js 에서는 이러한 모듈을 가져와 초기화하고 필요한 기능을 호출하게 하면 좋을 것 같습니다. test.html 의 body에는 <script src = "js/main.js " ..... > 와 같이 하면 유지보수되 쉽고 사용자 또한 알기 쉬운 코드가 될 수 있을 것 같습니다.

**Comment by kyahnu** [comment]
어차피 계속 캔버스를 쓰지는 않고 시각화 라이브러리와 그래프 처리하는 라이브러리 둘 다 써서 조합하든지 둘 중 하나만 쓰든지 하게 될 거 같습니다.

물론 그전에 코드를 모듈화할 수 있으면 더 좋겠죠
