### ISSUE TITLE
show.html의 drawSVGGraph가 정의되지 않았습니다.

### ISSUE THREAD

**Issue by Nhyojeong** [oss2024hnu/coursegraph-js#260]
show창에서 json 파일을 선택하면 drawSVGGraph가 정의되지 않았다는 'Show.html:51 Error parsing JSON: ReferenceError: drawSVGGraph is not defined at reader.onload' 오류가 발생하고 있습니다.

**Comment by kyagrd** [comment]
main.js를 지워서 그런 거 같군요 관련 함수만 일단 빼놓겠습니다.

**Comment by vegahouse102** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/261

**Comment by kyagrd** [comment]
396f74e6efca185c536820de22a967d1ae5a3483 로 해결 아 거으 동시에 해결했네요
