### ISSUE TITLE
반응형 디자인 추가

### ISSUE THREAD

**Issue by ychankk** [oss2024hnu/coursegraph-js#287]
CSS 미디어 쿼리를 사용하여 반응형 디자인을 구현해야하는데, 이는 다양한 화면 크기와 해상도에서 웹사이트의 접근성과 가독성을 보장하므로 추가하면 더 좋겠다고 생각합니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/290
