### ISSUE TITLE
검색 기능 추가

### ISSUE THREAD

**Issue by ychankk** [oss2024hnu/coursegraph-js#293]
과목명뿐만 아니라 교수명, 트랙, 학점 등 다양한 필터를 적용할 수 있는 검색 기능을 추가하여 사용자가 필요한 정보를 빠르게 찾을 수 있도록 하면 좋을 거 같습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/310
