### ISSUE TITLE
시각화 개선

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-js#295]
1. 줌, 팬, 툴팁과 같은 상호작용 기능을 추가하여 시각화를 개선합니다.
2. 색상 코드나 아이콘을 사용하여 다양한 코스 카테고리나 유형을 나타냅니다.

**Comment by kyagrd** [comment]
이런 일반적이고 추상적인 이슈는 이슈로 적당치 않아 반려합니다.
