### ISSUE TITLE
사용자 권한 관리

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-js#298]
사용자 권한을 추가하여 관리자와 일반 사용자가 애플리케이션을 다르게 사용할 수 있도록 하면 좋을거 같습니다.
관리자는 데이터를 추가, 수정, 삭제할 수 있지만 일반 사용자는 조회만 할 수 있도록 하면 좋을거같습니다.

**Comment by kyagrd** [comment]
막던지지 마세요 자꾸 이상한 이슈 넣으면 감점합니다.
