### ISSUE TITLE
input.html, input.js 추가 및 input.json 데이터 방식 변경이 필요합니다

### ISSUE THREAD

**Issue by hy2oning** [oss2024hnu/coursegraph-js#30]
input.json 데이터 파일만 생성된걸로 보이며, 현재 test.js에서 courses.json파일은 작동 가능하나,
input.json 데이터 파일 형식과 courses.json 데이터 파일 형식이 다르기 때문에 
기존 작성해둔 test.js 의 과목 생성이 불가능한거 같습니다.
데이터 파일 형식을 맞추거나 새롭게 과목 생성을 하는 코드가 필요할거 같습니다.

**Comment by kyahnu** [comment]
관련 PR이 머지되었기 때문에 해결된 것으로 보고 일단 닫겠습니다
