### ISSUE TITLE
creator main.js 입력 폼의 유효성 검사 부족

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-js#300]
입력 폼의 유효성 검사가 부족한거 같습니다.
JSON 파일 생성 시 데이터 형식의 일관성 검증이 필요한거 같습니다.

**Comment by kyagrd** [comment]
이렇게 추상적ㅇ로 구체적인 거 없이 써놓으면 남들이 어느 부ㅜㄴ이 문제인지 알고 고치나요? 

무성의하게 자꾸 이런 식으로 이슈 넣으면 감접합니다. 경고 여러 번 했습니다.
