### ISSUE TITLE
다크모드 후 png로 저장을 하면 다크모드로 저장되지 않습니다. 

### ISSUE THREAD

**Issue by Nhyojeong** [oss2024hnu/coursegraph-js#309]
subject-chart.html에서 다크모드로 변경한 후 png로 저장 버튼을 눌러 저장을 하면 저장된 사진은 다크모드를 하기 이전의 모습으로 저장이 됩니다. 다크모드를 하고 저장할시에 다크모드 상태가 유지되며 저장되어야 합니다.

**Comment by kyagrd** [comment]
이건 아니지 않나요? 다크모드는 그냥 화면에서 보기 위한 거고 이미지들은 보통 출력을 위해서라서 밝은 바탕이 기본입니다.

대부분의 웹사이트가 출력을 시키면 다크모드가 아닌 밝은 바탕으로 그래서 출력이 돼요. 이 이슈는 반려합니다.

일반적인 대부분의 웹사이트와 반대되는 기능을 원하는 건데 특별한 이유가 없으면 이렇게 할 이유가 없거든요.
