### ISSUE TITLE
cs-data.html, cs-data.js 추가 or cs-data.json 데이터 방식 변경이 필요합니다

### ISSUE THREAD

**Issue by hy2oning** [oss2024hnu/coursegraph-js#31]
#30 input.json과 마찬가지로 데이터 파일만 생성된걸로 보이며, cs-data.js 과목 생성 방식을 변경하거나, cs-data.json의 데이터방식의 변경이 필요할거같습니다.

**Comment by kyahnu** [comment]
이건 이미 해결된 듯
