### ISSUE TITLE
index.html 에서 <button>요소 내의 <a> 요소 사용

### ISSUE THREAD

**Issue by Retic02** [oss2024hnu/coursegraph-js#315]
구조적으로 이상한 형식이기에 변경이 필요하다고 생각합니다

**Comment by kyagrd** [comment]
맞아요 보통 반대로 되어 있거나 해야 하지 않나요? 꼼수를 쓰려고 해도.

제일 좋은 건 버튼 모양의 링크를 만들려면 a 태그에다 클래스 부여해서 그 클래스가 버튼 모양이 되도록 CSS를 거는 게 가장 깔끔하긴 하죠.

**Comment by kyagrd** [comment]
근데 input이 아니라 index.html 인 거 같군요. input.html 은 이제 안쓰니까

**Comment by kyagrd** [comment]
아 근데 index에는 이미 고쳐져 있네요. 너무 정신이 업어서 저거 고쳐진 것도 몰랐는데 ... 근데 input은 어차피 안쓰는데 실수로 안지워 노흥ㄴ 거니까 이슈 점수는 인정하되 바로 닫겠습니다. input.html 지웠어요 이제
