### ISSUE TITLE
 리셋 버튼

### ISSUE THREAD

**Issue by JianKong-1** [oss2024hnu/coursegraph-js#317]
위의 기능 버튼을 반복해서 누르면 인터페이스가 복구되지 않으므로, 리셋 버튼을 만드는 것을 제안합니다.
![2024-06-17 225059](https://github.com/oss2024hnu/coursegraph-js/assets/147126782/40ee9d3c-6636-4ff6-9cfb-1fd450a0d8f7)

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/322
