### ISSUE TITLE
1,2,3,4학년이 두번씩 나오는 오류가 발생했습니다.

### ISSUE THREAD

**Issue by ohnakyu** [oss2024hnu/coursegraph-js#318]
![dsa](https://github.com/oss2024hnu/coursegraph-js/assets/162093749/2db26281-a12b-4737-a27b-fe9a9b14f777)
1,2,3,4학년이 두번씩 나오는 오류가 발생했습니다. 버튼은 모두 정상적으로 작동합니다.

**Comment by kyagrd** [comment]
어떤 버전에서인지 적어 주세요 이슈에는

코드는 계속 PR이 들어오며 머지되면서 바뀌고 있기 때문에 어떤 버전인지 명시하지 않으면 이미 최신 버전에서 고쳐졌는지 어떤지 확인이 잘 안되고 혼란스럽습니ㅏㄷ.

**Comment by kyagrd** [comment]
제 기준으론 발생하지 않아서 이건 점수 취소하겠습니다. 어떤 버전에서 인지 알 수가 없으니

**Comment by ohnakyu** [comment]
d7145dcc1e98aa3f482838dfbb12b23b098eab82 버전에서 발생한 오류입니다.
