### ISSUE TITLE
피드백 및 평가 시스템 내용 추가

### ISSUE THREAD

**Issue by ychankk** [oss2024hnu/coursegraph-js#329]
강의 평가와 설문 조사 시스템을 추가하면 좋을 거 같습니다. 
내용으로는 학생들이 강의를 평가하고 피드백을 남길 수 있는 시스템을 추가하고 다양한 주제로 설문 조사를 진행하고 결과를 분석할 수 있는 기능을 제공할 수 있도록 하는 게 좋을 거 같습니다.

**Comment by kyagrd** [comment]
이런 너무 뜬금없은 이슈는 받지 않습니다. 프로젝트 주제와 한참 벗어낫어요

**Comment by ychankk** [comment]
넵 죄송합니다.
