### ISSUE TITLE
과목 개요 및 설명  기능 추가

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-js#330]
과목 개요 및 설명
각 과목명을 클릭시 간단한 설명이나 개요를 함께 제공하여 학생들이 과목의 내용과 특성을 이해하는 데 도움을 주는 기능을 추가하면 장기적인 관점에서 프로젝트가 더 완성도있을 거 같아서 기능 추가 이슈를 제안합니다.

**Comment by kyagrd** [comment]
이거 이 프로젝트 내요 ㅇ아니라니까요 계속 이걸 하는 사람들이 있네요 이슈로
