### ISSUE TITLE
학점 및 시간 정보  각 과목의 학점 수와 수업 시간 정보를 표시하는 기능 추가

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-js#331]
학점 및 시간 정보

각 과목의 학점 수와 수업 시간 정보를 표시하여 학생들이 효과적으로 시간표를 계획할 수 있도록 합니다.
이와 같은 다양한 정보를 포함하면 과목 이수 체계도가 학생들의 학업 계획 수립과 졸업 요건 충족에 큰 도움이 될 것입니다.

**Comment by kyagrd** [comment]
이러 프로젝트 주제 외의 내용 막 던지면 감점해야 할까요 앞으로 10점씩? 왜이려ㅓ나요 정말?

**Comment by peyoon** [comment]
네 죄송합니다.
