### ISSUE TITLE
이수체계도에서 각 과목을 누르는 버튼으로 바꾸어 간단한 정보를 나타내는 방법을 도입했으면 좋겠습니다.

### ISSUE THREAD

**Issue by yeonggwang123** [oss2024hnu/coursegraph-js#334]
![스크린샷 2024-06-17 231622](https://github.com/oss2024hnu/coursegraph-js/assets/93718815/13fa4e81-0344-4cf5-9523-9d78b183937a)

**Comment by kyagrd** [comment]
이미 비슷한 이슈가 올라왔습니다. 중복입니다.
