### ISSUE TITLE
전체적인 디자인 변경점

### ISSUE THREAD

**Issue by Jae20230112** [oss2024hnu/coursegraph-js#335]
pico css나 bootstrap을 통한 디자인 측면의 개선을 한다면 전체적인 디자인의 향상과 가독성이 좋아질 것 같습니다.

**Comment by kyagrd** [comment]
이런 이슈는 받지 않습니다. index.html 에서 기능 개선 말고 심미적 개선을 안받는다고 한 것과 같은 맥락입니다.

지금 기능도 자동화도 극히 안되어있는데 이걸 고민할 단계도 아니죠
