### ISSUE TITLE
다크모드 사용시 dummynode의 글씨가 보입니다.

### ISSUE THREAD

**Issue by Kim-Jong-Yun** [oss2024hnu/coursegraph-js#337]
![더미노드 글씨](https://github.com/oss2024hnu/coursegraph-js/assets/62275876/e69567de-7e1c-47ac-9868-4affa00ac5db)
![ㅇㅇㅇㅇㅇ](https://github.com/oss2024hnu/coursegraph-js/assets/62275876/768264e4-0ffe-4c42-8abe-f05de07f7fbd)

사용자 입장에서 보이지 않아야 하는 부분이라 생각이 듭니다

**Comment by Kim-Jong-Yun** [comment]
#344

**Comment by kyagrd** [comment]
근데 다크모드가 되긴 되나요? 왜 난 안되지 ...

**Comment by Kim-Jong-Yun** [comment]
> 근데 다크모드가 되긴 되나요? 왜 난 안되지 ...

#322 적용 이후로 안되는 것 같습니다

**Comment by vegahouse102** [comment]
https://github.com/oss2024hnu/coursegraph-js/issues/303
