### ISSUE TITLE
학년 버튼을 누르고 전공기초(필수), 공통권장과목을 클릭시 모든 과목이 활성화되는 오류가 발생합니다.

### ISSUE THREAD

**Issue by ohnakyu** [oss2024hnu/coursegraph-js#340]
학년 버튼을 누르고 전공기초(필수), 공통권장과목을 클릭시 모든 과목이 활성화되는 오류가 발생하는 것 같습니다.

**Comment by kyagrd** [comment]
아니 어느 html 파일에서요 정보를 제대로 제공해 주세요 반려합니다.

**Comment by ohnakyu** [comment]
Show.html 파일이고 7a95e86a7f0ebf807198d879a7d1ab35570f0dbd 버전입니다.
