### ISSUE TITLE
최신 버전 적용시 상단 버튼 작동 안합니다

### ISSUE THREAD

**Issue by Kim-Jong-Yun** [oss2024hnu/coursegraph-js#347]
이전 버전으로 돌려야 합니다

상단버튼 작동 안하는 것을 포함해
학년 버튼 기능이 이상해져서
배경이 투명해지고 있습니다

**Comment by kyagrd** [comment]
최신버전이 어느 버전인가요? 버전을 작성해 주세요. 계속 PR이 들어가고 잇어서 "최신버전"이라는 게 계속 바뀝니다.

**Comment by Kim-Jong-Yun** [comment]
> 최신버전이 어느 버전인가요? 버전을 작성해 주세요. 계속 PR이 들어가고 잇어서 "최신버전"이라는 게 계속 바뀝니다.

#322 마지막 머지 버전 입니다

**Comment by kyagrd** [comment]
> > 최신버전이 어느 버전인가요? 버전을 작성해 주세요. 계속 PR이 들어가고 잇어서 "최신버전"이라는 게 계속 바뀝니다.
> 
> #322 마지막 머지 버전 입니다

아뇨 그거 말고 sha1 해시코드요

아직 commit 버전을 모르고 프로젝트에 참여하고 있나요?

**Comment by kyagrd** [comment]
아 지금 sha1 코드를 세 개를 한꺼번에 가져오면 저중에서 뭘 말하는 건지 ... 맨 처음걸 말하는 건가요?

실습시간에 버진 히스토리에 시계 표시 누르면 죽 나오는 그거라고 ... 해봤을텐데요

**Comment by kyagrd** [comment]
지금 PR이 하나 더 머지되었는데 이것도 함께 해결된 건지 한번 확인해 부세요

**Comment by kyagrd** [comment]
그리고 어느 html 인가요 어느 파일이닞도 밝히지 않는 구체성 없는 제목과 내용은 이슈로 부적절하니 반려합니다.
