### ISSUE TITLE
python의 make test처럼 간단한 테스트를 할 수 있으면 좋겠습니다

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-js#349]
python의 make test처럼 js도 기본적으로 실행이 되는지 확인하고 올릴 수 있는 make test 기능이 있으면 좋겠습니다.

**Comment by kyagrd** [comment]
그걸 어떻게 할건데요 GUI로 마우스가 움직여야 하는데 웹은 ... 구체적인 방법론이아 툴이나 제시하지 않으므로 반려합니다.

사실 그래서 GUI도 테스트 자동화 못하고 있었잖아요 파이썬 쪽에서도

**Comment by kyagrd** [comment]
추상적으로 그냥 있었으면 좋겠다는 너무합니다.
