### ISSUE TITLE
최신버전 pull받았을때 실행 안되는 문제

### ISSUE THREAD

**Issue by kmin3625** [oss2024hnu/coursegraph-js#350]
![오류](https://github.com/oss2024hnu/coursegraph-js/assets/28837493/a6b1a850-f4d5-42df-8f78-4fe3e9807dec)
subject-chart.html 에 사진에 있는 부분 문제인것 같습니다.

**Comment by kyagrd** [comment]
이래서 테스트 자동화 플랜을 세워놓는게 프로젝트 진행에 중요합니다. 꼭 이렇게 깨먹는 사람들이 생기거든요 하 ...
