### ISSUE TITLE
통합된 파일이 필요할 것 같습니다.

### ISSUE THREAD

**Issue by lunatic280** [oss2024hnu/coursegraph-js#39]
현재 여러 html 파일이 있고 사용하려면 일일이 Live Server에서 실행시키거나 주소를 변경하여 html을 확인하는데 한 html파일에 현재 만들어진 html파일을 확인할 수 있으면 좋겠습니다.

**Comment by kyahnu** [comment]
이 이슈에서 어떤 내용을 개발하고 있는지 좀 정리한 후에 README에다 업데이트 하던가 합시다

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/82
