### ISSUE TITLE
README 파일에 vscode 기본설정, github 연결, 프로그램 설명 등 내용 추가

### ISSUE THREAD

**Issue by hy2oning** [oss2024hnu/coursegraph-js#4]
README 파일에 vscode 기본설정 및 github 연결하는방법, 프로그램 설명 등 내용이 추가되어야할거 같습니다

**Comment by kyahnu** [comment]
제목에 그냥 무슨 파일 변경 말고 조금은 구체적인 정보가 드러나도록 해주세요

**Comment by kyagrd** [comment]
이것도 대략적으로 진행된 거 같으니 이 이슈도 닫겠습니다.
