### ISSUE TITLE
courses 데이터 부분을 별도의 파일로 관리가 필요합니다

### ISSUE THREAD

**Issue by DoongDoongSJ** [oss2024hnu/coursegraph-js#44]
main.js 파일에 있는 courses 부분을 별도의 데이터 파일을 생성하여 관리하는 것이 바람직합니다

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-js/issues/43 동시다발적으로 올라온 이슈라서 닫음 점수는 인정
