### ISSUE TITLE
index.html 에서 CSS 및 JavaScript 파일의 경로를 절대 경로로 수정

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-js#47]
- 현재 코드에서는 CSS 및 JavaScript 파일의 경로가 상대 경로로 설정되어 있습니다. 즉 현재 작업 중인 파일의 위치를 기준으로 상대적으로 지정되어 있는걸로 파악됩니다. 
- 이는 파일이 있는 위치에 따라 경로가 달라질 수 있고 서버의 구조나 경로 변경 등의 문제가 발생할 수 있습니다, 또한 브라우저가 파일을 로드하지 못할 가능성도 있습니다. 
- 따라서 상대 경로 대신에 절대 경로를 사용하는 것이 좋을 것 같습니다. 
- 절대 경로를 사용하면 상대경로에 비해 안정성도 높아지고 유지보수도 쉬워지기 때문에 절대경로로 수정하는 것이 좋을 것 같습니다.

**Comment by kyahnu** [comment]
최상위 디렉토리를 /로 하자는 말이죠?

**Comment by kyahnu** [comment]
index.html은 어차피 원본 틀에 있던 거라 프로젝트 관련 내용이 아니라 삭제할 거라서 (삭제하자는 이슈도 이미 올라왔고)
다른 html 파일도 지금 상대경로로 되어 있나요?

**Comment by stayineverywhere** [comment]
현재는 디렉터리에 따라 js/custom.js 등으로 되어 있는데, 이것을 /js/custom.js 로 변경하면
해당 HTML이 변경되더라도 동작할 것 같습니다.

**Comment by stayineverywhere** [comment]
> index.html은 어차피 원본 틀에 있던 거라 프로젝트 관련 내용이 아니라 삭제할 거라서 (삭제하자는 이슈도 이미 올라왔고) 다른 html 파일도 지금 상대경로로 되어 있나요?

네. show.html 도 루트 기준으로 PATH 가 설정되어있지 않고 현재 디렉토리로 되어 있어서 show.html을 이동시키면 상대경로로 지정이 될 가능성이 높을것 같습니다.

**Comment by kyagrd** [comment]
지금 대부분 이제 절대경로로 하고 있는 거ㅏ 같아 일단 이수ㅠ 닫습니다
