### ISSUE TITLE
js 디렉토리에 html을 넣지 맙시다

### ISSUE THREAD

**Issue by kyahnu** [oss2024hnu/coursegraph-js#50]
b2f22c674df9e65abcff64d3044a9ebae14b593d 버전 기준으로 현재 

Show.html 인가 html 파일 하나가 js 디렉토리에 들어 있는데요,
js 디렉토리에는 js 파일들 모아놓으라고 만든 디렉토리잖아요 디렉토리 이름만 봐도.
최상위 디렉토리로 옮기거나 합시다.

**Comment by leesang01** [comment]
#51 로 해결
