### ISSUE TITLE
텍스트가 노드 밖으로 나오기에 수정할 필요가 있습니다.

### ISSUE THREAD

**Issue by shofjablas** [oss2024hnu/coursegraph-js#61]
![image](https://github.com/oss2024hnu/coursegraph-js/assets/97035336/608e2850-aa4b-4afa-8159-10752b5d1dcc)

**Comment by kyagrd** [comment]
이거 지금 버전에선 해결된 건가요?

**Comment by shofjablas** [comment]
넵 현재 버전으로 해결되었습니다.
![image](https://github.com/oss2024hnu/coursegraph-js/assets/97035336/e5fc45ee-e13d-4865-a615-7d2bb9a7bc45)
