### ISSUE TITLE
컴퓨터 네트워크, 블록체인, 캡스톤 디자인의 노드가 잘리기에 코드를 수정해야할 것 같습니다.

### ISSUE THREAD

**Issue by shofjablas** [oss2024hnu/coursegraph-js#63]
![image](https://github.com/oss2024hnu/coursegraph-js/assets/97035336/d5dd5f6f-00d0-401a-acc4-ed68521b9643)

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/80 이걸로 해결됨
