### ISSUE TITLE
그래프가 노드 위로 지나는 문제와 일부 그래프가 겹치는 문제를 해결해야 될 것 같습니다.

### ISSUE THREAD

**Issue by IVEGAEUL** [oss2024hnu/coursegraph-js#64]
현재, show.html에서 그래프가 노드 위로 지나는 문제와,  그래프의 방향이 겹치는 문제를 해결해야 될 것 같습니다. 과목 노드 위치를 변경하거나, 그래프 방향을 수정할 필요가 있어 보입니다.

**Comment by kyagrd** [comment]
그래프와 노드의 정의를 이상하게 쓰고 있어서 문장의 뜻이 통하지 않아 반려합니다.

그래프는 노드와 엣지(화살표 등) 으로 이루어져 있으니까 노드는 그래프를 이루는 구성요소인데 겹친다니 무슨 이야긴지 ...

의미가 불명확한 이슈는 반려합니다.
