### ISSUE TITLE
test.html 이 작동하지 않습니다. 

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-js#67]
- 원래 작동이 되었는지 않되었는지는 모르겠지만 현재로서는 작동을 하지 않기에 이를 개선해야 할 것 같습니다. 
- h1 태그 이외에 아무것도 나타나지 않고 있습니다.

**Comment by kyahnu** [comment]
동시다발적으로 올라와서 점수는 인정하지만 앞으로 관련 논의는 여기서 해주세요
https://github.com/oss2024hnu/coursegraph-js/issues/65
