### ISSUE TITLE
클래스 다이어그램 형태로 제작을 시작하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-js#7]
클래스 다이어그램의 특성
시스템의 정적 구조를 나타내는 UML다이어그램의 한 유형입니다.
클래스, 속성, 메서드 간의 관계를 보여줍니다.
객체지향 설계에서 청사진으로 많이 이용되고있습니다.

![클래스간 관계](https://github.com/oss2024hnu/coursegraph-js/assets/162516396/9fb8bd15-dfca-4a87-8b80-83264e760a3c)

![클래스 상속](https://github.com/oss2024hnu/coursegraph-js/assets/162516396/4b81b75d-36b5-48bd-b252-2bc15b79784d)

위에 첨부한 사진처럼 관계와 상속을 표시할 수 있습니다.

**Comment by kyahnu** [comment]
이거는 과목 표시를 위한건가요 아니면 프로젝트 코드 구조를 잡기 위해서 하자는 건가요?

**Comment by JWhyeok** [comment]
UML다이어그램 형태를 활용하면 프로젝트에서 원하는 이수체계도를 그릴 수 있을것 같아 제안해봤습니다.

**Comment by kyagrd** [comment]
이후 이에 대한 논의가 사실상 없어서 이 이슈는 닫습니다.
