### ISSUE TITLE
파일들에 대한 정리가 필요해 보입니다.

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-js#70]
da05d38 버전에서 
md 파일은 onboarding 폴더에, 
html 파일은 html 파일에,
json 파일은 data 파일에 넣는 것이 좋아보입니다

**Comment by kyagrd** [comment]
일단 html 파일은 최상위 디렉토리에 남겨둬도 될 거 같습니다. 아직 개수가 많지 않아서

**Comment by kyagrd** [comment]
json 파일을 옮기는 거는 이미 그동안 PR을 통해 해결이 되어서 현재 3775e3a5d29593e4f4251bed0fb85b8b18ae1c3b 버전에서는 정리가 된 상황인 거 같습니다.

**Comment by kyagrd** [comment]
그런데 md 파일은 지금 README.md 하나밖에 없잖아요. 그래서 아직 옮길 게 없는 거 같으니 이 이슈는 닫겠습니다.
