### ISSUE TITLE
데이터 파일을 자동으로 받을 수 있게 해야합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-js#72]
subject-chart 에서 과목을 직접 수기로 입력해서 받았는데, 현재 데이터 파일도 따로 존재하기 때문에 자동으로 입력받을 수 있도록 해야합니다.

**Comment by kyagrd** [comment]
동시다발적으로 유사한 올라와서 점수는 인정하지만 관련 이슈에서 몰아서 논의하기로 하고 이건 닫습니다

https://github.com/oss2024hnu/coursegraph-js/issues/73
