### ISSUE TITLE
파일들을 정리할때 경로 위치도 파악하면서 변경해야할것 같습니다.

### ISSUE THREAD

**Issue by shofjablas** [oss2024hnu/coursegraph-js#75]

**Comment by kyagrd** [comment]
이런 일반적인 것은 이슈로 적절하지 않습니다.
구체적으로 어디서 무슨 파일이 잘못되었다다도 아니고
무슨 새로운 정책을 결정하자는 거나 문서화를 하자는 것도 아니고요. 반려합니다.

이런 식으로 무성의하게 이슈를 작성하지 말아주세요.
