### ISSUE TITLE
각각 파일들의 사용법에 대한 문서화가 필요합니다. 

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-js#77]
- 파일을 입력 받아야 하는 경우 등 어떤 파일을 선택해야 하는 지 등 문서화를 해야 할 것 같습니다. 
- 파일이 무슨 역할을 하는 지 , 뭐 하는 지 대략 정리하는 것이 좋을 것 같습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/issues/164 본인이 올린 사실상 중복 혹은 조금 더 내용이 추가된 이슈라, 어차피 이 이슈에 댓글도 안달렸으니 앞으로는 새로 올리는 이슈에서 관련 논의를 계속하도록 합시다.
