### ISSUE TITLE
js 파일 안에 있는 html 파일을 밖으로 빼야합니다

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-js#79]
![IMG_6702](https://github.com/oss2024hnu/coursegraph-js/assets/91938434/1f5f4f4b-889a-40d1-8c19-1a311fc42862)

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/issues/50
이미 올라온 이슈입니다 중복된 이슈를 올리지 마세요

이슈를 올릴 때닌 기존에 올라온 이슈 내용을 확인하고 이슈 작성 바랍니다.

반려합니다
