### ISSUE TITLE
json역시 데이터의 형식을 지정해야합니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-js#81]
각기 다른 형식의 데이터를 공유하며 프로그램을 제작하기는 어려울 것 같습니다.

**Comment by kyagrd** [comment]
장기적으로는 YAML에서 저동으로 JSON을 생성하던가 직접 YAML라이브러를 쓴다면 YAML라이브러리의 데이터 형식을 그대로 활용하던가 해야겠죠.

**Comment by kyagrd** [comment]
그냥 js-yaml 로 파이썬 저장소의 데이터를 읽어서 작업하는 게 좋을 거 같습니다.

**Comment by kyahnu** [comment]
이제 yaml에서 자동생성된 걸로 하기로 해서 이 이슈는 닫으면 될 듯
