### ISSUE TITLE
파이썬 프로젝트와 같은 데이터 형식(YAML)으로부터 과목을 읽어들일 수 있도록 합시다

### ISSUE THREAD

**Issue by IVEGAEUL** [oss2024hnu/coursegraph-js#9]
아직까지 베타로 만들고 수정하지 않아서 인지 현재 출력되고 있는 것은 교과목이 아닌 게임 이름명이 출력되고 있습니다.
컴퓨터 공학과 학생들이 듣는 수업으로 교과목을 수정해서 올릴 필요가 있습니다.

**Comment by shofjablas** [comment]
컴퓨터공학과 수업에서 듣는 과목들 json파일로 올렸습니다.

**Comment by kyahnu** [comment]
> 컴퓨터공학과 수업에서 듣는 과목들 json파일로 올렸습니다.

프로젝트마다 다른 데이터 형식을 사용하는 것보다는 원본 형식은 하나의 형식을 기준으로 하는 것이 좋을 거 같습니다.
이미 파이썬에서 YAML로 하고 있으니 YAML 데이터로부터 JSON이 필요하다면 자동으로 변환하는 것도 방법입니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-js/pull/23 로 이슈는 해결된 듯 합니다.

**Comment by kyagrd** [comment]
이 주제에 신기하게도 참여자들의 관심이 적은 거 같아, 일단 제가 ChatGPT에게 물어봤습니다

https://chatgpt.com/share/43094917-fc55-4c46-a700-7889c30c1851

이렇게 하면 파이썬 프로젝트의 YAML파일 데이터를 직접 가져와서 작업할 수 있습니다.
