### ISSUE TITLE
코드스페이스에서 작업하는 사람들을 위해 README에 추가

### ISSUE THREAD

**Issue by gwanghyeon123** [oss2024hnu/coursegraph-js#90]
코드스페이스에서 작업하는 사람들을 위한것을 readme에 추가
파이썬으로 웹서버를 띄우는방법을 추가해주세요.

**Comment by kyagrd** [comment]
이것도 처음 참여하는 사람들이 해결을 도전해볼만한 문서 내용 변경/추가 이슈입니다. 처음 참여하는 분들은 이 이슈를 공략하면 좋을 거 같네요.
