### ISSUE TITLE
데이터 파일 경로가 맞는지 확인하는 코드를 추가할 수 있습니다.

### ISSUE THREAD

**Issue by chuunbyul** [oss2024hnu/coursegraph-js#92]
만약을 위해 데이터 파일 경로 확인: fetch('/data/courses.json')에서 JSON 파일 경로가 올바른지 확인하는 코드를 추가해야 한다고 생각합니다.
JSON 파일 경로를 확인하고, 경로가 올바르지 않으면 오류 메시지를 출력하도록 합니다.

filePath 변수: JSON 파일 경로를 지정합니다.
fetch 요청: 파일을 비동기로 가져오며, 응답 상태를 확인합니다. 응답 상태가 ok가 아니면 오류를 발생시킵니다.
오류 처리: fetch 요청이 실패하면 콘솔에 오류 메시지를 출력하고, 사용자에게 경로를 확인하라는 알림 메시지를 표시합니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-js/issues/49 중복 이슈이므로 반려
